// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_duBAB9bhvES3liAgQ4hQ8ib3CUAWH50',
    appId: '1:131255903185:web:c21e252be3a16abf9276f0',
    messagingSenderId: '131255903185',
    projectId: 'ecommerce-flutter-b8503',
    authDomain: 'ecommerce-flutter-b8503.firebaseapp.com',
    storageBucket: 'ecommerce-flutter-b8503.appspot.com',
    measurementId: 'G-Z8PD28R30F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAp-NW7ULm6uYwsj3WC79nDUTz_tLV934',
    appId: '1:131255903185:android:f63c013b058ac3a99276f0',
    messagingSenderId: '131255903185',
    projectId: 'ecommerce-flutter-b8503',
    storageBucket: 'ecommerce-flutter-b8503.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlwy_2wfSO_XgEhcbmad70gswKxTdTV2I',
    appId: '1:131255903185:ios:81677a856cfb035e9276f0',
    messagingSenderId: '131255903185',
    projectId: 'ecommerce-flutter-b8503',
    storageBucket: 'ecommerce-flutter-b8503.appspot.com',
    iosBundleId: 'com.example.ecommerceFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlwy_2wfSO_XgEhcbmad70gswKxTdTV2I',
    appId: '1:131255903185:ios:6c36014e5706c6f89276f0',
    messagingSenderId: '131255903185',
    projectId: 'ecommerce-flutter-b8503',
    storageBucket: 'ecommerce-flutter-b8503.appspot.com',
    iosBundleId: 'com.example.ecommerceFlutter.RunnerTests',
  );
}
